name: "CI Tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: "Ruby ${{ matrix.ruby }}, Rails ${{ matrix.gemfile }}"

    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - "6.1"
          - "7.0"
          - "7.1"
        ruby:
          - "3.0.0"
          - "3.1.0"
          - "3.2.2"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.gemfile }}.gemfile
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: "Install Ruby ${{ matrix.ruby  }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: "Reset app database"
        run: |
          bundle exec rake fake:db:reset
          bundle exec rake fake:db:test:prepare

      - name: "Run tests without acceptance"
        run: |
          bundle exec rake test

      - name: "Run acceptance tests for RSpec"
        run: |
          bundle add rspec-rails
          bundle exec rake TEST=test/acceptance/testing_test.rb TESTOPTS="--name='test_rspec_tests'"

      - name: "Run acceptance tests for TestUnit"
        run: |
          bundle remove rspec-rails
          bundle exec rake TEST=test/acceptance/testing_test.rb TESTOPTS="--name='test_test_unit_tests'"
